#!/usr/bin/env ruby
# -*- mode: ruby; -*-

# https://github.com/palantir/python-language-server

if `which pip`.length == 0
  puts 'Install pip before running this script.'
else
  puts 'Installing pythong-language-server...'
  puts `pip install 'python-language-server[all]'`
  puts `Finished installing python-language-server.`
end
